"""
Entities module for file and archive representations.
"""

from .compressed_archive import (
    ArchiveHandler,
    ArchiveHandlerChain,
    CompressedArchive,
    Bzip2Archive,
    Bzip2Handler,
    GzipArchive,
    GzipHandler,
    TarBz2Archive,
    TarBz2Handler,
    TarGzArchive,
    TarGzHandler,
    TarXzArchive,
    TarXzHandler,
    XzArchive,
    XzHandler,
    RarArchive,
    RarHandler,
    SevenZipArchive,
    SevenZipHandler,
    ZipArchive,
    ZipHandler,
    get_archive_manager,
)
from .file import File

__all__ = [
    "File",
    "CompressedArchive",
    "ZipArchive",
    "Bzip2Archive",
    "GzipArchive",
    "TarGzArchive",
    "TarBz2Archive",
    "TarXzArchive",
    "XzArchive",
    "RarArchive",
    "SevenZipArchive",
    "ArchiveHandler",
    "ZipHandler",
    "Bzip2Handler",
    "GzipHandler",
    "TarGzHandler",
    "TarBz2Handler",
    "TarXzHandler",
    "XzHandler",
    "RarHandler",
    "SevenZipHandler",
    "ArchiveHandlerChain",
    "get_archive_manager",
]
